(()=>{const R=window.RB_ACTION_REG;if(!R)return;
R.registerSpells('Sorcerer',[
['Banishment',4,'save','Banish a creature to another plane while concentration lasts','CHA'],['Blight',4,'save','8d8 necrotic damage','CON'],['Dimension Door',4,'effect','Teleport yourself and one willing creature up to 500 ft',''],['Greater Invisibility',4,'effect','Target remains invisible even while attacking or casting',''],['Polymorph',4,'save','Transform a creature into a beast while concentrating','WIS'],['Wall of Fire',4,'save','Create a damaging wall of flame','DEX'],
['Animate Objects',5,'effect','Animate up to ten nonmagical objects to fight for you',''],['Cloudkill',5,'save','Moving poisonous cloud; 5d8 poison','CON'],['Cone of Cold',5,'save','60-ft cone; 8d8 cold','CON'],['Dominate Person',5,'save','Charm and control a humanoid','WIS'],['Hold Monster',5,'save','Paralyse a creature','WIS'],['Telekinesis',5,'effect','Move or restrain creatures and objects with force',''],
['Chain Lightning',6,'save','10d8 lightning to a primary target and up to three others','DEX'],['Disintegrate',6,'save','10d6 + 40 force damage','DEX'],['Eyebite',6,'save','Inflict sleep, panic, or sickness with repeated gazes','WIS'],['Globe of Invulnerability',6,'effect','Barrier blocks lower-level spells from outside',''],['Mass Suggestion',6,'save','Compel up to twelve creatures with a reasonable course','WIS'],['Sunbeam',6,'save','6d8 radiant line; may blind; repeat on later actions','CON'],
['Delayed Blast Fireball',7,'save','12d6 fire that grows while delayed','DEX'],['Finger of Death',7,'save','7d8 + 30 necrotic damage','CON'],['Fire Storm',7,'save','Ten 10-ft cubes; 7d10 fire','DEX'],['Plane Shift',7,'effect','Travel to another plane or attempt to banish a creature',''],['Prismatic Spray',7,'save','Cone produces a random powerful coloured ray effect','DEX'],['Teleport',7,'effect','Teleport a group and carried objects over great distance',''],
['Dominate Monster',8,'save','Charm and control a creature','WIS'],['Incendiary Cloud',8,'save','Moving cloud; 10d8 fire','DEX'],['Power Word Stun',8,'effect','Stun a creature with 150 HP or fewer',''],['Sunburst',8,'save','60-ft radius; 12d6 radiant and possible blindness','CON'],['Earthquake',8,'effect','Create severe tremors, fissures, and collapsing structures',''],
['Gate',9,'effect','Open a portal to another plane and optionally call a creature',''],['Meteor Swarm',9,'save','Four impacts; 20d6 fire + 20d6 bludgeoning','DEX'],['Power Word Kill',9,'effect','A creature with 100 HP or fewer dies',''],['Time Stop',9,'effect','Take 1d4+1 turns while time is stopped for others',''],['Wish',9,'effect','Duplicate powerful magic or attempt a greater reality-altering wish','']
]);
R.registerSpells('Wizard',[
['Arcane Eye',4,'effect','Create an invisible movable magical sensor',''],['Banishment',4,'save','Banish a creature to another plane while concentration lasts','CHA'],['Fire Shield',4,'effect','Gain heat/cold protection and damage nearby attackers',''],['Greater Invisibility',4,'effect','Target remains invisible even while attacking or casting',''],['Polymorph',4,'save','Transform a creature into a beast while concentrating','WIS'],['Wall of Fire',4,'save','Create a damaging wall of flame','DEX'],
['Animate Objects',5,'effect','Animate up to ten nonmagical objects to fight for you',''],['Cloudkill',5,'save','Moving poisonous cloud; 5d8 poison','CON'],['Cone of Cold',5,'save','60-ft cone; 8d8 cold','CON'],['Hold Monster',5,'save','Paralyse a creature','WIS'],['Telekinesis',5,'effect','Move or restrain creatures and objects with force',''],['Wall of Force',5,'effect','Create an invisible wall immune to ordinary damage',''],
['Chain Lightning',6,'save','10d8 lightning to a primary target and up to three others','DEX'],['Disintegrate',6,'save','10d6 + 40 force damage','DEX'],['Globe of Invulnerability',6,'effect','Barrier blocks lower-level spells from outside',''],['Mass Suggestion',6,'save','Compel up to twelve creatures with a reasonable course','WIS'],['Sunbeam',6,'save','6d8 radiant line; may blind; repeat on later actions','CON'],['True Seeing',6,'effect','Grant truesight, notice secret doors, and see into Ethereal Plane',''],
['Finger of Death',7,'save','7d8 + 30 necrotic damage','CON'],['Forcecage',7,'effect','Trap creatures inside an invisible magical cage',''],['Plane Shift',7,'effect','Travel to another plane or attempt to banish a creature',''],['Prismatic Spray',7,'save','Cone produces a random powerful coloured ray effect','DEX'],['Reverse Gravity',7,'effect','Reverse gravity in a large cylindrical area',''],['Teleport',7,'effect','Teleport a group and carried objects over great distance',''],
['Antimagic Field',8,'effect','Suppress magic in a 10-ft-radius sphere around you',''],['Dominate Monster',8,'save','Charm and control a creature','WIS'],['Maze',8,'effect','Banish a creature into a labyrinthine demiplane',''],['Mind Blank',8,'effect','Protect a creature from psychic damage and mind-affecting magic',''],['Power Word Stun',8,'effect','Stun a creature with 150 HP or fewer',''],['Sunburst',8,'save','60-ft radius; 12d6 radiant and possible blindness','CON'],
['Foresight',9,'effect','Grant powerful advantage and defensive foresight for 8 hours',''],['Meteor Swarm',9,'save','Four impacts; 20d6 fire + 20d6 bludgeoning','DEX'],['Power Word Kill',9,'effect','A creature with 100 HP or fewer dies',''],['Time Stop',9,'effect','Take 1d4+1 turns while time is stopped for others',''],['True Polymorph',9,'save','Transform a creature or object into another form','WIS'],['Wish',9,'effect','Duplicate powerful magic or attempt a greater reality-altering wish','']
]);
R.registerSpells('Bard',[
['Confusion',4,'save','Confuse creatures in an area, disrupting their actions','WIS'],['Dimension Door',4,'effect','Teleport yourself and one willing creature up to 500 ft',''],['Freedom of Movement',4,'effect','Target ignores many restraints and movement impediments',''],['Greater Invisibility',4,'effect','Target remains invisible even while attacking or casting',''],['Polymorph',4,'save','Transform a creature into a beast while concentrating','WIS'],
['Animate Objects',5,'effect','Animate up to ten nonmagical objects to fight for you',''],['Dominate Person',5,'save','Charm and control a humanoid','WIS'],['Greater Restoration',5,'effect','End a major debilitating effect on a creature',''],['Hold Monster',5,'save','Paralyse a creature','WIS'],['Mass Cure Wounds',5,'effect','Heal up to six creatures for 3d8 + spell ability',''],['Teleportation Circle',5,'effect','Create a portal to a known permanent teleportation circle',''],
['Eyebite',6,'save','Inflict sleep, panic, or sickness with repeated gazes','WIS'],['Mass Suggestion',6,'save','Compel up to twelve creatures with a reasonable course','WIS'],['Otto’s Irresistible Dance',6,'effect','Force a creature to dance and hinder its movement and defence',''],['Programmed Illusion',6,'effect','Create an illusion that activates when a condition occurs',''],['True Seeing',6,'effect','Grant truesight, notice secret doors, and see into Ethereal Plane',''],
['Etherealness',7,'effect','Enter the Ethereal Plane temporarily',''],['Forcecage',7,'effect','Trap creatures inside an invisible magical cage',''],['Regenerate',7,'effect','Restore 4d8+15 HP and ongoing healing; regrow body parts',''],['Resurrection',7,'effect','Return a creature dead up to a century to life',''],['Teleport',7,'effect','Teleport a group and carried objects over great distance',''],
['Dominate Monster',8,'save','Charm and control a creature','WIS'],['Feeblemind',8,'save','4d6 psychic and devastate Intelligence/Charisma','INT'],['Glibness',8,'effect','Charisma checks treat rolls of 14 or lower as 15',''],['Mind Blank',8,'effect','Protect a creature from psychic damage and mind-affecting magic',''],['Power Word Stun',8,'effect','Stun a creature with 150 HP or fewer',''],
['Foresight',9,'effect','Grant powerful advantage and defensive foresight for 8 hours',''],['Power Word Kill',9,'effect','A creature with 100 HP or fewer dies',''],['True Polymorph',9,'save','Transform a creature or object into another form','WIS']
]);
R.registerSpells('Cleric',[
['Banishment',4,'save','Banish a creature to another plane while concentration lasts','CHA'],['Death Ward',4,'effect','Prevent one death or drop to 0 HP',''],['Freedom of Movement',4,'effect','Target ignores many restraints and movement impediments',''],['Guardian of Faith',4,'save','Summon a guardian that deals radiant damage to nearby enemies','DEX'],['Stone Shape',4,'effect','Reshape a Medium-sized section of stone',''],
['Flame Strike',5,'save','4d6 fire + 4d6 radiant in a vertical cylinder','DEX'],['Greater Restoration',5,'effect','End a major debilitating effect on a creature',''],['Mass Cure Wounds',5,'effect','Heal up to six creatures for 3d8 + spell ability',''],['Raise Dead',5,'effect','Return a creature dead up to 10 days to life',''],['Scrying',5,'save','Observe a creature at great distance through a magical sensor','WIS'],
['Blade Barrier',6,'save','Wall of blades; 6d10 slashing','DEX'],['Harm',6,'save','14d6 necrotic and reduce maximum HP','CON'],['Heal',6,'effect','Restore 70 HP and end blindness/deafness/disease',''],['Heroes’ Feast',6,'effect','Feast grants major long-duration defensive benefits',''],['True Seeing',6,'effect','Grant truesight, notice secret doors, and see into Ethereal Plane',''],
['Divine Word',7,'effect','Powerful word affects enemies according to their current HP',''],['Fire Storm',7,'save','Ten 10-ft cubes; 7d10 fire','DEX'],['Plane Shift',7,'effect','Travel to another plane or attempt to banish a creature',''],['Regenerate',7,'effect','Restore 4d8+15 HP and ongoing healing; regrow body parts',''],['Resurrection',7,'effect','Return a creature dead up to a century to life',''],
['Antimagic Field',8,'effect','Suppress magic in a 10-ft-radius sphere around you',''],['Control Weather',8,'effect','Change regional weather over several minutes',''],['Earthquake',8,'effect','Create severe tremors, fissures, and collapsing structures',''],['Holy Aura',8,'effect','Allies gain strong defences; fiends/undead risk blindness',''],
['Astral Projection',9,'effect','Project a group into the Astral Plane',''],['Gate',9,'effect','Open a portal to another plane and optionally call a creature',''],['Mass Heal',9,'effect','Distribute 700 HP of healing among creatures you can see',''],['True Resurrection',9,'effect','Restore a creature dead up to 200 years to life','']
]);
R.registerSpells('Druid',[
['Blight',4,'save','8d8 necrotic damage','CON'],['Freedom of Movement',4,'effect','Target ignores many restraints and movement impediments',''],['Ice Storm',4,'save','2d8 bludgeoning + 4d6 cold in a 20-ft radius','DEX'],['Polymorph',4,'save','Transform a creature into a beast while concentrating','WIS'],['Wall of Fire',4,'save','Create a damaging wall of flame','DEX'],
['Greater Restoration',5,'effect','End a major debilitating effect on a creature',''],['Insect Plague',5,'save','20-ft sphere; 4d10 piercing and difficult terrain','CON'],['Mass Cure Wounds',5,'effect','Heal up to six creatures for 3d8 + spell ability',''],['Tree Stride',5,'effect','Step into a tree and emerge from another tree repeatedly',''],['Wall of Stone',5,'effect','Create a durable wall made of stone panels',''],
['Heal',6,'effect','Restore 70 HP and end blindness/deafness/disease',''],['Heroes’ Feast',6,'effect','Feast grants major long-duration defensive benefits',''],['Sunbeam',6,'save','6d8 radiant line; may blind; repeat on later actions','CON'],['Transport via Plants',6,'effect','Travel instantly between large plants on the same plane',''],['Wall of Thorns',6,'effect','Create a thick damaging wall of thorns',''],
['Fire Storm',7,'save','Ten 10-ft cubes; 7d10 fire','DEX'],['Mirage Arcane',7,'effect','Reshape the apparent terrain across a large area',''],['Plane Shift',7,'effect','Travel to another plane or attempt to banish a creature',''],['Regenerate',7,'effect','Restore 4d8+15 HP and ongoing healing; regrow body parts',''],['Reverse Gravity',7,'effect','Reverse gravity in a large cylindrical area',''],
['Animal Shapes',8,'effect','Transform willing creatures into beasts',''],['Control Weather',8,'effect','Change regional weather over several minutes',''],['Earthquake',8,'effect','Create severe tremors, fissures, and collapsing structures',''],['Feeblemind',8,'save','4d6 psychic and devastate Intelligence/Charisma','INT'],['Sunburst',8,'save','60-ft radius; 12d6 radiant and possible blindness','CON'],
['Foresight',9,'effect','Grant powerful advantage and defensive foresight for 8 hours',''],['Shapechange',9,'effect','Transform yourself into other creature forms while retaining key abilities',''],['Storm of Vengeance',9,'effect','Create a vast multi-round supernatural storm',''],['True Resurrection',9,'effect','Restore a creature dead up to 200 years to life','']
]);
R.registerSpells('Warlock',[
['Banishment',4,'save','Banish a creature to another plane while concentration lasts','CHA'],['Blight',4,'save','8d8 necrotic damage','CON'],['Dimension Door',4,'effect','Teleport yourself and one willing creature up to 500 ft',''],['Hallucinatory Terrain',4,'effect','Make natural terrain look, sound, and smell like other terrain',''],
['Contact Other Plane',5,'effect','Ask up to five questions of an extraplanar entity',''],['Dream',5,'effect','Enter a known creature’s dreams as messenger or threat',''],['Hold Monster',5,'save','Paralyse a creature','WIS'],['Scrying',5,'save','Observe a creature at great distance through a magical sensor','WIS'],
['Circle of Death',6,'save','60-ft radius; 8d6 necrotic','CON'],['Eyebite',6,'save','Inflict sleep, panic, or sickness with repeated gazes','WIS'],['Flesh to Stone',6,'save','Restrain and potentially petrify a creature','CON'],['Mass Suggestion',6,'save','Compel up to twelve creatures with a reasonable course','WIS'],['True Seeing',6,'effect','Grant truesight, notice secret doors, and see into Ethereal Plane',''],
['Etherealness',7,'effect','Enter the Ethereal Plane temporarily',''],['Finger of Death',7,'save','7d8 + 30 necrotic damage','CON'],['Forcecage',7,'effect','Trap creatures inside an invisible magical cage',''],['Plane Shift',7,'effect','Travel to another plane or attempt to banish a creature',''],
['Demiplane',8,'effect','Open a door to a small extradimensional chamber',''],['Dominate Monster',8,'save','Charm and control a creature','WIS'],['Feeblemind',8,'save','4d6 psychic and devastate Intelligence/Charisma','INT'],['Glibness',8,'effect','Charisma checks treat rolls of 14 or lower as 15',''],['Power Word Stun',8,'effect','Stun a creature with 150 HP or fewer',''],
['Astral Projection',9,'effect','Project a group into the Astral Plane',''],['Foresight',9,'effect','Grant powerful advantage and defensive foresight for 8 hours',''],['Imprisonment',9,'effect','Magically imprison a creature until a specified release condition',''],['Power Word Kill',9,'effect','A creature with 100 HP or fewer dies',''],['True Polymorph',9,'save','Transform a creature or object into another form','WIS']
]);
R.registerSpells('Paladin',[
['Banishment',4,'save','Banish a creature to another plane while concentration lasts','CHA'],['Death Ward',4,'effect','Prevent one death or drop to 0 HP',''],['Locate Creature',4,'effect','Sense the direction to a familiar creature within range',''],['Dispel Evil and Good',5,'effect','Gain protection from certain supernatural creatures and end effects',''],['Geas',5,'save','Place a long-duration magical command on a creature','WIS'],['Raise Dead',5,'effect','Return a creature dead up to 10 days to life','']
]);
R.registerSpells('Ranger',[
['Conjure Woodland Beings',4,'effect','Summon fey creatures that obey your commands',''],['Freedom of Movement',4,'effect','Target ignores many restraints and movement impediments',''],['Locate Creature',4,'effect','Sense the direction to a familiar creature within range',''],['Stoneskin',4,'effect','Grant resistance to nonmagical bludgeoning, piercing, and slashing',''],['Commune with Nature',5,'effect','Learn several facts about the surrounding natural region',''],['Tree Stride',5,'effect','Step into a tree and emerge from another tree repeatedly','']
]);
})();